#!/usr/bin/env perl

use warnings;
use strict;

use File::Which qw(which);
use Carp qw(croak);


my $s3cmd = 's3cmd';
my $site_path = "$ENV{HOME}/public_html";
my $site_name = 'TylerCipriani';
my $bucket = 'tylercipriani.com';

# Name of subpath in site
my $bucket_prefix = '';

my @cssfiles = ('local.css', 'style.css', 'static/css/merkel-dag-d3.css');

sub update {
    chdir($site_path);
    if ( not -f "$site_name/index.html" ) {
        die("Could not find $site_name/index.html in $site_path");
    }

    if ( not $bucket_prefix ) {
        $bucket_prefix = '/';
    }

    if ( not $bucket_prefix =~ /\/$/) {
        $bucket_prefix .= '/';
    }

    my @cmd = ($s3cmd, 'sync');
    push(@cmd, "--add-header='Expires:max-age=604800'");
    push(@cmd, "--exclude '.git/*'");
    push(@cmd, "--exclude 'robots.txt'");
    push(@cmd, "--acl-public");
    push(@cmd, $site_name . '/');
    push(@cmd, 's3://' . $bucket . $bucket_prefix);

    system(join(' ', @cmd));

    my @csscmd = ($s3cmd, 'setacl');
    push(@csscmd, '--acl-public', "--mime-type='text/css'");

    my @cssheaderscmd = ($s3cmd, 'modify');
    push(@cssheaderscmd, "--add-header='Content-type:text/css'");

    foreach my $css (@cssfiles) {
        my $s3css = 's3://' . $bucket . $bucket_prefix . $css;
        system(join(' ', @csscmd) . ' ' . $s3css);
        system(join(' ', @cssheaderscmd) . ' ' . $s3css);
    }
}

sub main {
    $s3cmd = which($s3cmd);

    if ( not -x "$s3cmd" ) {
        croak("Couldn't find s3cmd");
    }

    update;
}

main;
